server:
  host: "0.0.0.0"
  port: 8090
polling:
  interval: 60 # 1 minute
  url: "http://localhost:10101/alerts"

detector:
  batch_gap_threshold: 15
  time_delta: 5
  confidence_threshold: 0.2

  initial_alpha: 1
  initial_beta: 1

  delay: 5

historic_data:
  path: "./test_data/alerts.csv"
