version: 1
disable_existing_loggers: false

formatters:
  default:
    format: "%(asctime)s - %(threadName)s - %(name)s - %(levelname)s - %(message)s"
    datefmt: "%Y-%m-%d %H:%M:%S"

handlers:
  console:
    class: logging.StreamHandler
    level: DEBUG
    formatter: default
    stream: ext://sys.stdout

  file:
    class: logging.FileHandler
    level: INFO
    formatter: default
    filename: app.log
    mode: a

loggers:
  src:
    level: DEBUG
    handlers: []
    propagate: false

root:
  level: WARNING
  handlers: []
